# Generated by Django 4.0.4 on 2022-04-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_portfoliocategory_remove_portfolio_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.portfoliocategory'),
            preserve_default=False,
        ),
    ]
