# Generated by Django 4.0.4 on 2022-04-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioCategory',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('img', models.ImageField(upload_to='')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
