# Generated by Django 4.0.4 on 2022-04-28 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_rename_portfoliocategory_category_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(max_length=50),
        ),
    ]
